### ISSUE TITLE
恢复包安装与命令安装在登录LinuxQQ时均会闪退

### ISSUE THREAD

**Issue by D1ongX** [initialencounter/chronocat-termux#1]

**Comment by initialencounter** [comment]
LinuxQQ版本必须是 linuxqq_3.1.2-13107_arm64.deb

**Comment by initialencounter** [comment]
首次登录闪退是有可能的，原因未知，正在排查，重启之后可以稳定运行

**Comment by misaka20002** [comment]
大大我们来自同一个q群，可以一起交流下吗

**Comment by initialencounter** [comment]
> 大大我们来自同一个q群，可以一起交流下吗

可以的，在哪个群？

**Comment by D1ongX** [comment]
版本确认过了正确，重启后仍然闪退，听说是因为检测到了LiteLoaderQQNT 插件qq自己退出了

**Comment by initialencounter** [comment]
> 版本确认过了正确，重启后仍然闪退，听说是因为检测到了LiteLoaderQQNT 插件qq自己退出了

确定恢复包也会闪退吗？麻烦提供一下用  `qq` 命令启动后，闪退的控制台输出的信息

**Comment by D1ongX** [comment]
VNC不好复制控制台输出信息，加一下qq吧 3083652808 好发截图，恢复包和手动安装的报错还不一样
恢复包是system_bus_socket：没有那个文件或目录
手动安装是system_bus_socket：拒绝连接
